### ISSUE TITLE
Feature Tracker for v1

### ISSUE THREAD

**Issue by sheridanchris** [sheridanchris/ProjectManagementSolution#1]
v1 checklist

- [ ] Real-time capabilities
- [ ] Issue and feature tracking
- [ ] Calendars and timelines
- [ ] Kanban boards
- [ ] Agile sprints
- [ ] Administration
